export enum ButtonVariant {
	PRIMARY = 'PRIMARY',
	SECONDARY = 'SECONDARY',
	GHOST = 'GHOST',
	TERTIARY = 'TERTIARY',
	PRIMARY_DANGER = 'PRIMARY--DANGER',
	PRIMARY_SUCCESS = 'PRIMARY--SUCCESS',
	SECONDARY_DANGER = 'SECONDARY--DANGER',
	SECONDARY_SUCCESS = 'SECONDARY--SUCCESS',
}

export enum ButtonSize {
	LARGE = 'LARGE',
	COMPACT = 'COMPACT',
}

export enum Layout {
	INLINE = 'INLINE',
	COLUMN = 'COLUMN',
}
